### ISSUE TITLE
error Exception (-2147352567

### ISSUE THREAD

**Issue by ZGTPGT** [adb014/nsf2x#12]
Hi, i tried to convert a Notes Archive an getting this error. Any Idea?

```
INFO : Lotus Notes NSF file to EML, MBOX and PST file converter.
INFO : Contact dbateman@free.fr for more information.

INFO : Connection to Notes established

INFO : Starting Convert : 2018-03-14 08:11:13.085213

INFO : Converting : C:\_Heinzel\_Archive export\Archiv Angebote aus Archiv.nsf 
INFO : Starting MIME encoding of messages
ERROR : Error converting database Archiv Angebote aus Archiv.nsf
ERROR : Exception (-2147352567, 'Ausnahmefehler aufgetreten.', (0, 'NotesView', 'Notes-Fehler: Diese Ansicht ist veraltet und erfordert fehlende Feldliste. Bitte ändern und Ansicht erneut speichern. ((Stationery))', None, 0, -2147217499), None) :
ERROR : Traceback (most recent call last):
  File "nsf2x.py", line 679, in doConvertDirectory
  File "nsf2x.py", line 755, in realConvert
  File "C:\Logiciel\WinPython-32bit-3.4.4.4Qt5\python-3.4.4\lib\site-packages\win32com\client\dynamic.py", line 516, in __getattr__
pywintypes.com_error: (-2147352567, 'Ausnahmefehler aufgetreten.', (0, 'NotesView', 'Notes-Fehler: Diese Ansicht ist veraltet und erfordert fehlende Feldliste. Bitte ändern und Ansicht erneut speichern. ((Stationery))', None, 0, -2147217499), None)

INFO : End of convert : 2018-03-14 08:11:14.116567
```

**Comment by adb014** [comment]
Ok, thats a new one. Lotus Notes keeps the messages stored in the NSF files and then extracts "Views" to these messages that are lists of messages. This allows past searches to be kept and to easily find previously used files. In you case you have a "View" called "Stationary" that Lotus says is invalid. Probably you NSF file was created with an older version of Lotus.

I really should be flagging an error in this case and should just ignore the view and continue. This is a relatively minor change and I'll include it in a future version, but am waiting for other changes to including in a new version


D.
