### ISSUE TITLE
unamble to  (error-2147467259)

### ISSUE THREAD

**Issue by jarq11** [adb014/nsf2x#13]
I'm trying to convert NSF to PST, but receive error when Your app is on step when importing previously exported .eml to PST file. 
It look using MAPI failed.

(run with NO PST helper)
INFO : Connection to Notes established
INFO : Starting Convert : 2018-03-14 09:49:12.298639
INFO : Converting : C:\Users\(...)atest1.nsf 
INFO : Starting MIME encoding of messages
INFO : Opening PST file - C:\Users\(...)atest1.pst
ERROR : Could not connect to MAPI !
ERROR : Exception (-2147467259, 'Unspecified error', None, None) :
ERROR : Error converting database d_atest1.nsf
ERROR : Exception (-2147467259, 'Unspecified error', None, None) :
ERROR : Traceback (most recent call last):
  File "nsf2x.py", line 679, in doConvertDirectory
  File "nsf2x.py", line 824, in realConvert
  File "C:\Logiciel\nsf2x\mapiex.py", line 300, in __init__
pywintypes.com_error: (connect to MAPI), 'Unspecified error', None, None)
INFO : End of convert : 2018-03-14 09:49:26.258970

(run with PST Helper)
INFO : Starting Convert : 2018-03-14 10:12:48.579165
INFO : Forcing use of external helper function
INFO : Using external helper function 'helper32/eml2pst.exe' for importation of the EML files
INFO : Converting : C:\Users\(...)atest1.nsf 
INFO : Starting MIME encoding of messages
INFO : Starting exportation to temporary EML messages
INFO : Starting importation of EML files into PST file
INFO : Importing EML files in C:\Users\(...)atest1.pst
ERROR : Helper process return the error code (255)
ERROR : Traceback (most recent call last):
ERROR :   File "eml2pst.py", line 56, in <module>
ERROR :   File "C:\Logiciel\nsf2x\mapiex.py", line 300, in __init__
ERROR : pywintypes.com_error: (-2147467259, 'Unspecified error', None, None)
ERROR : Importation of EML files into PST is incomplete
INFO : Removing temporary EML files
INFO : Finished populating : atest1
INFO : Exceptions: 0 ... Documents OK : 5 Untreated : 0
INFO : End of convert : 2018-03-14 10:13:14.498935

I did a suspenseful conversion in the past (September 2017) with 1.3.3 ver, but it looks problem is not in nsf2x version but with changed OUTLMIME.DLL (my o365 was updated last time)

Is it related to your question on stackoverflow in topic "MAPI IconverterSession MAPItoMIME function importing raw MIME text with Outlook 2016 C2R"? from Oct. 2017? - (...)Does this mean that MIMEtoMAPI is no longer available(...) Is there a means to continue to use MIMEtoMAPI ? (...)

I also can open exported  .eml in outlook but importing to PST doesn't work
Is it know issue? Any progress in this ? any workaround.

**Comment by ZGTPGT** [comment]
same issue here (Office 365).
I now import the eml files with "ReliefJet essentials" to a new pst. Not the best way but a workaround.

**Comment by adb014** [comment]
This doesn't seem to be related to the MimeToMAPI problems with o365. Rather the MAPIInitalize function is returning an error. This means that you installation of Office no longer gives a MAPI provider or some other error. Not knowing your setup, you'll need to look at the possible sources of errors with MAPIInitalize on the page

https://msdn.microsoft.com/en-us/library/office/cc842343.aspx

and try to resolve the problem. As this doesn't seem to be a problem with NSF2X itself, I'll close this issue
