### ISSUE TITLE
Wrong Linked Files?

### ISSUE THREAD

**Issue by tpmodding** [adb014/nsf2x#20]
Hey, i try to convert Louts Archive to PST with your .exe file...should it possible that some file locations are hardcoded? because i am getting this information

INFO : Lotus Notes NSF file to EML, MBOX and PST file converter.
INFO : Contact dbateman@free.fr for more information.

INFO : Connection to Notes established

INFO : Starting Convert : 2018-11-19 16:14:04.860040

INFO : Forcing use of external helper function
INFO : Using external helper function 'helper32/eml2pst.exe' for importation of the EML files
INFO : Converting : D:****31.nsf 
INFO : Starting MIME encoding of messages
INFO : Starting exportation to temporary EML messages
INFO : Creating directory C:\***Sent
INFO : Creating directory C:\***Inbox
ERROR : Ignoring message 938 of form 'Memo' without MIME body
ERROR : #### Subject : ***
INFO : Creating directory C:\***IT
ERROR : Ignoring message 1233 of form 'Memo' without MIME body
ERROR : #### Subject : ***
ERROR : Ignoring message 1235 of form 'Memo' without MIME body
ERROR : #### Subject : ***
ERROR : Ignoring message 1246 of form 'Memo' without MIME body
ERROR : #### Subject : ***
INFO : Creating directory C:\***Recruiting
***...***
INFO : Creating directory C:\***
INFO : Starting importation of EML files into PST file
ERROR : Helper process return the error code (255)
ERROR : Traceback (most recent call last):
ERROR :   File "C:\Logiciel\WinPython-32bit-3.4.4.4Qt5\python-3.4.4\lib\site-packages\win32com\client\dynamic.py", line 89, in _GetGoodDispatch
ERROR : pywintypes.com_error: (-2147221021, 'Vorgang nicht verfügbar.', None, None)
ERROR : 
ERROR : During handling of the above exception, another exception occurred:
ERROR : 
ERROR : Traceback (most recent call last):
ERROR :   File "eml2pst.py", line 46, in <module>
ERROR :   File "C:\Logiciel\WinPython-32bit-3.4.4.4Qt5\python-3.4.4\lib\site-packages\win32com\client\__init__.py", line 95, in Dispatch
ERROR :   File "C:\Logiciel\WinPython-32bit-3.4.4.4Qt5\python-3.4.4\lib\site-packages\win32com\client\dynamic.py", line 114, in _GetGoodDispatchAndUserName
ERROR :   File "C:\Logiciel\WinPython-32bit-3.4.4.4Qt5\python-3.4.4\lib\site-packages\win32com\client\dynamic.py", line 91, in _GetGoodDispatch
ERROR : pywintypes.com_error: (-2146959355, 'Starten des Servers fehlgeschlagen', None, None)
ERROR : Importation of EML files into PST is incomplete
INFO : Removing temporary EML files
INFO : Finished populating : a_uids31
INFO : Exceptions: 4 ... Documents OK : 2235 Untreated : 0

INFO : Converting : D:\***31.nsf 
INFO : Starting MIME encoding of messages

(censored some informations with ***)

But I dont have a path with C:\Logiciel\WinPython-32bit-3.4.4.4Qt5 ....

Thanks!

**Comment by adb014** [comment]
This is a new one. I use Py2Exe to convert the python code to an executable. Effectively the directory you are seeing is where I built the code, but Py2Exe should have supplied all of the dependencies necessary. The only way I can see what you are seeing as happening is if the install has been corrupted in some manner and the required dependencies are not available.

Can you trying removing and reinstalling NSF2X 

D.

**Comment by tpmodding** [comment]
I saw i had installed 1.3.3, updated to 1.3.5 but have the same issues...

INFO : Starting importation of EML files into PST file
ERROR : Helper process return the error code (255)
ERROR : Traceback (most recent call last):
ERROR :   File "C:\Logiciel\WinPython-32bit-3.4.4.4Qt5\python-3.4.4\lib\site-packages\win32com\client\dynamic.py", line 89, in _GetGoodDispatch
ERROR : pywintypes.com_error: (-2147221021, 'Vorgang nicht verfügbar.', None, None)
ERROR : 
ERROR : During handling of the above exception, another exception occurred:
ERROR : 
ERROR : Traceback (most recent call last):
ERROR :   File "eml2pst.py", line 46, in <module>
ERROR :   File "C:\Logiciel\WinPython-32bit-3.4.4.4Qt5\python-3.4.4\lib\site-packages\win32com\client\__init__.py", line 95, in Dispatch
ERROR :   File "C:\Logiciel\WinPython-32bit-3.4.4.4Qt5\python-3.4.4\lib\site-packages\win32com\client\dynamic.py", line 114, in _GetGoodDispatchAndUserName
ERROR :   File "C:\Logiciel\WinPython-32bit-3.4.4.4Qt5\python-3.4.4\lib\site-packages\win32com\client\dynamic.py", line 91, in _GetGoodDispatch
ERROR : pywintypes.com_error: (-2146959355, 'Starten des Servers fehlgeschlagen', None, None)
ERROR : Importation of EML files into PST is incomplete
INFO : Removing temporary EML files
INFO : Finished populating : a_uids31
INFO : Exceptions: 4 ... Documents OK : 2235 Untreated : 0

**Comment by adb014** [comment]
Is your version of outlook really 64bit, while Lotus is 32bit ? Can you disable le "helper function" in the options of NSF2X ? Is this after the conversion of the first NSF file and the failure is on the second file as it appears in the original message ?  If so the workaround is to convert one file at a time.

David

**Comment by tpmodding** [comment]
Outlook 2016 MSO (16.0.9126.2336) 32-Bit

IBM Notes 9 Release 9.0.1FP6

Both are x86 but Windows is 64bit System, and i use your x86 release

But with the new release nothing works any more? :-/

I struggeld a lot but at the end the convertion "works"...kind of...

If I convert it to pst...everything looks ver crypted :S (see attachm.)

If I convert it to eml...i got only files like "1.eml" etc...each email one eml...

If I convert it to mbox...i dont know how to open it with outlook :D 

![unbenannt](https://user-images.githubusercontent.com/17259976/51334996-4c04d800-1a81-11e9-8865-cba373fbf7f0.JPG)

**Comment by adb014** [comment]
The function IConverterSession:MIMEToMAPI in microsofts MAPI API doesn't seem to be working. This is exactly the problem I have been seeing with O365, though you don't appear to be using 0365 at all. IF as you say it worked (partially) beforehand, your problem might be the key to trying to fix this probleme for 0365 as well

Unfortunately after many hours of trying to fix this problem with O365 I'm no closer to a solution, and am loathe to waste more time without a certainty of a fix. You're welcome to try and find the solution. Look in the code around the MIMEToMAPI function and how it is called

David

**Comment by tpmodding** [comment]
Ok, good to know. So wich version of outlook do i need to install that it would work?

**Comment by adb014** [comment]
I personally have Lotus Note 8.5 32bit et Office 2013 (Not 0365!) and it works fine

David
