### ISSUE TITLE
AttributeError: function 'MMCreateConvControls' not found

### ISSUE THREAD

**Issue by amouley** [adb014/nsf2x#22]
Hello All !

I'm trying to convert some NSF files to EML files with no luck. I have the following errors in nsf2x.log : 

`Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Logiciel\WinPython-32bit-3.4.4.4Qt5\python-3.4.4\lib\tkinter\__init__.py", line 1538, in __call__
    return self.func(*args)
  File "nsf2x.py", line 612, in doConvert
  File "nsf2x.py", line 679, in doConvertDirectory
  File "nsf2x.py", line 746, in realConvert
  File "nsf2x.py", line 127, in __init__
  File "nsf2x.py", line 183, in __SetDLLReturnTypes
  File "C:\Logiciel\WinPython-32bit-3.4.4.4Qt5\python-3.4.4\lib\ctypes\__init__.py", line 364, in __getattr__
    func = self.__getitem__(name)
  File "C:\Logiciel\WinPython-32bit-3.4.4.4Qt5\python-3.4.4\lib\ctypes\__init__.py", line 369, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'MMCreateConvControls' not found
`

I've installed WinPython-32bit-3.4.4.4Qt5 in the C:\Logiciel\ directory but it haven't resolved the problem. Please Help me. Thanks in advance.

**Comment by adb014** [comment]
You shouldn't need to install Winpython. The error abour MMCreateConvControls being missing implies that you nnotes.dll file is missing this function. If you have visual Studio installed the command

    dumpbin /exports nnotes.dll

should tell you if the MMCreateConvControls function exists in this DLL. Otherwise all I can suspect is that this function is moves in your version of Lotus Notes and I'll need you help to identifiy where it is

D.

**Comment by amouley** [comment]
Hello adb014,

Thanks a lot for your response. So a checked the dll and yes it doesn't contain the function MMCreateConvControls. Should i search for another dll that contains this function ? Thanks in advance.

Kind Regards.

**Comment by adb014** [comment]
Yes please, If you can tell me which DLL has this function I can get NSF2X to work for your case

D.

**Comment by alfonsrv** [comment]
Can confirm this function is not available in Lotus Notes 7. The 8.5 DLL has `MMCreateConvControls`.
