### ISSUE TITLE
ValueError: unsupported format character '?' (0xa) at index 24

### ISSUE THREAD

**Issue by dev107** [adb014/nsf2x#23]
With all tries, I got a bunch of following errors:

ValueError: unsupported format character '?' (0xa) at index 24
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Logiciel\WinPython-32bit-3.4.4.4Qt5\python-3.4.4\lib\tkinter\__init__.py", line 1538, in __call__
  File "nsf2x.py", line 612, in doConvert
  File "nsf2x.py", line 638, in doConvertDirectory

Its running on Windows 7, Lotus Notes 8.5.3 and Outlook 2010. I also tried mbox/eml. Same summary. Any hints?

**Comment by mtbandi** [comment]
I get the same error. 

Win10, Lotus 8.5, Outlook Office 365

**Comment by eizedev** [comment]
I am having the same problem and using the same version(s) as @mtbandi 
@adb014 any idea how to fix this? I have tested version 1.3.6 (x86). 1.3.3 and 1.3.5 generally not working.

Thanks

**Comment by ballerbude** [comment]
Unfortunately, same error.

@adb014 you have any idea, or is this project completely abandoned? Thank you.

**Comment by adb014** [comment]
Can’t test ´cause I no longer have NOTES, which was kind of the point of writing this code Le 11 nov. 2025 à 10:53, ballerbude ***@***.***> a écrit :﻿ballerbude left a comment (adb014/nsf2x#23)
Unfortunately, same error.
@adb014 you have any idea, or is this project completely abandoned? Thank you.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/adb014/nsf2x/issues/23#issuecomment-3515940621",
"url": "https://github.com/adb014/nsf2x/issues/23#issuecomment-3515940621",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
