### ISSUE TITLE
Exception in Tkinter callback

### ISSUE THREAD

**Issue by Nob1042** [adb014/nsf2x#25]
Hello, I have the following error while nsf2x open the session.
setup:
_Windows 7 Prof. SP1 64bit, 8GB
Lotus notes Release 9.0.1FP7 32-bit
Outlook for Office 365 MSO 16.0 32-bit
nsf2x-1.3.6-x86 32-bit_

I open nsf2x, then enter my nodes id password, path to NSF and PST, set options and start conversion but nothing happends, even hours later. No CPU-time or storage changes
No response to STOP; only close the window.
out of the log file:
_Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Logiciel\WinPython-32bit-3.4.4.4Qt5\python-3.4.4\lib\tkinter\__init__.py", line 1538, in __call__
  File "nsf2x.py", line 612, in doConvert
  File "nsf2x.py", line 638, in doConvertDirectory_
same massages repeat a couple of time
any idea? Thanks!

**Comment by Nob1042** [comment]
No comment? No idea?

**Comment by dieterkoenig** [comment]
Same problem here - seems that #23 is also about this observation
@adb014 is there any workaround?

**Comment by dieterkoenig** [comment]
**@all** - just retried with 1.3.3 - it works - so this may be a problem of 1.3.6

**Comment by Nob1042** [comment]
@dieterkoenig - you are right, 1.3.3 works but only EML and MBOX; PST only gives an error
I tried 1.3.5 as well and here PST works as well without an error - but emails are not imported proper into the PST-file; folders and sub-folders are correct and I can see all single mails but only as some kind of text-code; the columns (from, to, date, subject and so on) are not filled.... :((
any idea or workaround? Thanks.

**Comment by N4n0Ch33ry137** [comment]
@adb014 Hey, i have the same problem with version 1.3.6 while trying to produce a pst-file. "
to me it's not possible to install any software (some restrictions) so i only can run the non-install-version in 1.3.6

Do you have any idea how to fix?
