### ISSUE TITLE
Error - Could not connect to Outlook

### ISSUE THREAD

**Issue by sandeepgp** [adb014/nsf2x#34]
After completion 7.7% conversion, getting below error

INFO : Starting MIME encoding of messages
ERROR : Could not connect to Outlook !
ERROR : Exception (-2146959355, 'Server execution failed', None, None) :

Can someone please help here

**Comment by sandeepgp** [comment]
Below is the log generated

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Logiciel\WinPython-32bit-3.4.4.4Qt5\python-3.4.4\lib\tkinter\__init__.py", line 1538, in __call__
  File "nsf2x.py", line 612, in doConvert
  File "nsf2x.py", line 679, in doConvertDirectory
  File "nsf2x.py", line 825, in realConvert
AttributeError: 'NoneType' object has no attribute 'GetNamespace'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Logiciel\WinPython-32bit-3.4.4.4Qt5\python-3.4.4\lib\tkinter\__init__.py", line 1538, in __call__
  File "nsf2x.py", line 612, in doConvert
  File "nsf2x.py", line 679, in doConvertDirectory
  File "nsf2x.py", line 825, in realConvert
AttributeError: 'NoneType' object has no attribute 'GetNamespace'
