### ISSUE TITLE
nfs2x error

### ISSUE THREAD

**Issue by adamsla** [adb014/nsf2x#4]
So, thanks for the tool.  Not working for me.  I have Lotus Notes 9.x and Outlook 365.  The Lotus Notes 9.x is x86 (32bit), and Outlook 365 appears to be (amd64).  When doing the conversion I get exceptions as shown below.  This is latest version as of this post.

ERROR : #### Subject : blah blah blah
ERROR : Exception for message 99 ((-2147221164, 'Class not registered', None, None)) :
ERROR : Traceback (most recent call last):
  File "nsf2x.py", line 975, in realConvert
  File "C:\Logiciel\nsf2x\mapiex.py", line 248, in ImportEML
  File "C:\Logiciel\nsf2x\mapiex.py", line 88, in ImportEML
  File "C:\Logiciel\nsf2x\mapiex.py", line 317, in MimeToMapi
pywintypes.com_error: (-2147221164, 'Class not registered', None, None)

Any clues?

**Comment by adb014** [comment]
I'm actual away from the office for the next  2 weeks and so will have difficulties to reply.

This error is the classic error for the fact that Office 365 abuses the registry to allow multiple versions of Office to be installed. The installer of NSF2X tries to detect Office :365, or wh

**Comment by adb014** [comment]
Sorry answering from a phone makes it easy to make errors. The installer of NSF2X tries to detect Office 365, or what Microsoft calls ClickToRun, and tries to patch the registry. The NSF2X will give a huge warning in this case. So here are the possible problems

1) NSF2X correctly detected ClickToRun but you chose not to let the installer patch the registry
2) NSF2X correctly detected ClickToRun and you chose it let the installer patch the registry but it did it incorrectly for your case
3) NSF2X didn't detect ClickToRun in your case

For the first case try reinstalling. For the other two nothing I can do for two weeks, but google "ClickToRun MAPI" and there is a Microsoft tech site with the commands needed to manually patch to registry and I'll look at it when I get back. 

D.

**Comment by adb014** [comment]
Adam, were you able to get NSF2X to work by following the instructions on 

https://blogs.msdn.microsoft.com/stephen_griffin/2014/04/21/outlook-2013-click-to-run-and-com-interfaces/

See the section MAPI <-> MIME. If you were I'll be able to fix your problem, otherwise more digging will be needed

D.

**Comment by adamsla** [comment]
I will test shortly.
